Traceback (most recent call last):
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.10.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Gaming-Laptop\Desktop\Toontown-Advance\tools\compileDNA.py", line 106, in <module>
    process_single_file(file)
  File "C:\Users\Gaming-Laptop\Desktop\Toontown-Advance\tools\compileDNA.py", line 67, in process_single_file
    rootData = loadDNAFile(dnaStore, filename)
  File "C:\Users\Gaming-Laptop\Desktop\Toontown-Advance\tools\compileDNA.py", line 55, in loadDNAFile
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: 'toontown_central_sz.dna'
